const { convertTsvsToListWords } = require('../src/convertTsvsToListWords/index')
const { tsvs } = require('../mocks/mocks')
const { describe, expect, test } = require('@jest/globals')

const getShort = (tsvs) => {
  let shortTsvs = {}
  for (const key in tsvs) {
    if (Object.hasOwnProperty.call(tsvs, key)) {
      shortTsvs[key] = tsvs[key]
      return shortTsvs
    }
  }
}
const shortTsvs = getShort(tsvs)

describe('convertTsvsToListWords', () => {
  test('try to convertTsvsToListWords', () => {
    expect(convertTsvsToListWords(shortTsvs)).toEqual({
      listWordsInChapter: {
        '1': {
          'rc://*/tw/dict/bible/kt/jesus': '1',
          'rc://*/tw/dict/bible/kt/christ': '1',
          'rc://*/tw/dict/bible/names/david': '1',
          'rc://*/tw/dict/bible/names/abraham': '1',
          'rc://*/tw/dict/bible/names/isaac': '2',
          'rc://*/tw/dict/bible/names/jacob': '2',
          'rc://*/tw/dict/bible/names/judah': '2',
          'rc://*/tw/dict/bible/names/tamar': '3',
          'rc://*/tw/dict/bible/names/boaz': '5',
          'rc://*/tw/dict/bible/names/rahab': '5',
          'rc://*/tw/dict/bible/names/ruth': '5',
          'rc://*/tw/dict/bible/names/jesse': '5',
          'rc://*/tw/dict/bible/other/king': '6',
          'rc://*/tw/dict/bible/names/solomon': '6',
          'rc://*/tw/dict/bible/names/uriah': '6',
          'rc://*/tw/dict/bible/names/rehoboam': '7',
          'rc://*/tw/dict/bible/names/abijah': '7',
          'rc://*/tw/dict/bible/names/asa': '7',
          'rc://*/tw/dict/bible/names/jehoshaphat': '8',
          'rc://*/tw/dict/bible/names/jehoram': '8',
          'rc://*/tw/dict/bible/names/uzziah': '8',
          'rc://*/tw/dict/bible/names/jotham': '9',
          'rc://*/tw/dict/bible/names/ahaz': '9',
          'rc://*/tw/dict/bible/names/hezekiah': '9',
          'rc://*/tw/dict/bible/names/manasseh': '10',
          'rc://*/tw/dict/bible/names/josiah': '10',
          'rc://*/tw/dict/bible/names/babylon': '11',
          'rc://*/tw/dict/bible/names/zerubbabel': '12',
          'rc://*/tw/dict/bible/names/eliakim': '13',
          'rc://*/tw/dict/bible/names/zadok': '14',
          'rc://*/tw/dict/bible/names/eleazar': '15',
          'rc://*/tw/dict/bible/names/josephnt': '16',
          'rc://*/tw/dict/bible/names/mary': '16',
          'rc://*/tw/dict/bible/kt/call': '16',
          'rc://*/tw/dict/bible/other/generation': '17',
          'rc://*/tw/dict/bible/other/womb': '18',
          'rc://*/tw/dict/bible/other/conceive': '18',
          'rc://*/tw/dict/bible/kt/holyspirit': '18',
          'rc://*/tw/dict/bible/kt/righteous': '19',
          'rc://*/tw/dict/bible/kt/angel': '20',
          'rc://*/tw/dict/bible/kt/lord': '20',
          'rc://*/tw/dict/bible/other/dream': '20',
          'rc://*/tw/dict/bible/kt/fear': '20',
          'rc://*/tw/dict/bible/other/bear': '21',
          'rc://*/tw/dict/bible/kt/name': '21',
          'rc://*/tw/dict/bible/kt/save': '21',
          'rc://*/tw/dict/bible/other/peoplegroup': '21',
          'rc://*/tw/dict/bible/kt/peopleofgod': '21',
          'rc://*/tw/dict/bible/kt/sin': '21',
          'rc://*/tw/dict/bible/kt/fulfill': '22',
          'rc://*/tw/dict/bible/kt/prophet': '22',
          'rc://*/tw/dict/bible/other/virgin': '23',
          'rc://*/tw/dict/bible/other/interpret': '23',
          'rc://*/tw/dict/bible/kt/god': '23',
          'rc://*/tw/dict/bible/other/like': '24',
          'rc://*/tw/dict/bible/other/know': '25',
        },
      },
      listWordsInBook: {
        'rc://*/tw/dict/bible/kt/jesus': ['1:1', '1:16', '1:18', '1:21', '1:25'],
        'rc://*/tw/dict/bible/kt/christ': ['1:1', '1:16', '1:17', '1:18'],
        'rc://*/tw/dict/bible/names/david': ['1:1', '1:6', '1:17', '1:20'],
        'rc://*/tw/dict/bible/names/abraham': ['1:1', '1:2', '1:17'],
        'rc://*/tw/dict/bible/names/isaac': ['1:2'],
        'rc://*/tw/dict/bible/names/jacob': ['1:2', '1:15', '1:16'],
        'rc://*/tw/dict/bible/names/judah': ['1:2', '1:3'],
        'rc://*/tw/dict/bible/names/tamar': ['1:3'],
        'rc://*/tw/dict/bible/names/boaz': ['1:5'],
        'rc://*/tw/dict/bible/names/rahab': ['1:5'],
        'rc://*/tw/dict/bible/names/ruth': ['1:5'],
        'rc://*/tw/dict/bible/names/jesse': ['1:5', '1:6'],
        'rc://*/tw/dict/bible/other/king': ['1:6'],
        'rc://*/tw/dict/bible/names/solomon': ['1:6', '1:7'],
        'rc://*/tw/dict/bible/names/uriah': ['1:6'],
        'rc://*/tw/dict/bible/names/rehoboam': ['1:7'],
        'rc://*/tw/dict/bible/names/abijah': ['1:7'],
        'rc://*/tw/dict/bible/names/asa': ['1:7', '1:8'],
        'rc://*/tw/dict/bible/names/jehoshaphat': ['1:8'],
        'rc://*/tw/dict/bible/names/jehoram': ['1:8'],
        'rc://*/tw/dict/bible/names/uzziah': ['1:8', '1:9'],
        'rc://*/tw/dict/bible/names/jotham': ['1:9'],
        'rc://*/tw/dict/bible/names/ahaz': ['1:9'],
        'rc://*/tw/dict/bible/names/hezekiah': ['1:9', '1:10'],
        'rc://*/tw/dict/bible/names/manasseh': ['1:10'],
        'rc://*/tw/dict/bible/names/josiah': ['1:10', '1:11'],
        'rc://*/tw/dict/bible/names/babylon': ['1:11', '1:12', '1:17'],
        'rc://*/tw/dict/bible/names/zerubbabel': ['1:12', '1:13'],
        'rc://*/tw/dict/bible/names/eliakim': ['1:13'],
        'rc://*/tw/dict/bible/names/zadok': ['1:14'],
        'rc://*/tw/dict/bible/names/eleazar': ['1:15'],
        'rc://*/tw/dict/bible/names/josephnt': ['1:16', '1:18', '1:19', '1:20', '1:24'],
        'rc://*/tw/dict/bible/names/mary': ['1:16', '1:18', '1:20'],
        'rc://*/tw/dict/bible/kt/call': ['1:16', '1:21', '1:23', '1:25'],
        'rc://*/tw/dict/bible/other/generation': ['1:17'],
        'rc://*/tw/dict/bible/other/womb': ['1:18', '1:23'],
        'rc://*/tw/dict/bible/other/conceive': ['1:18', '1:20', '1:23'],
        'rc://*/tw/dict/bible/kt/holyspirit': ['1:18', '1:20'],
        'rc://*/tw/dict/bible/kt/righteous': ['1:19'],
        'rc://*/tw/dict/bible/kt/angel': ['1:20', '1:24'],
        'rc://*/tw/dict/bible/kt/lord': ['1:20', '1:22', '1:24'],
        'rc://*/tw/dict/bible/other/dream': ['1:20'],
        'rc://*/tw/dict/bible/kt/fear': ['1:20'],
        'rc://*/tw/dict/bible/other/bear': ['1:21', '1:23'],
        'rc://*/tw/dict/bible/kt/name': ['1:21', '1:23', '1:25'],
        'rc://*/tw/dict/bible/kt/save': ['1:21'],
        'rc://*/tw/dict/bible/other/peoplegroup': ['1:21'],
        'rc://*/tw/dict/bible/kt/peopleofgod': ['1:21'],
        'rc://*/tw/dict/bible/kt/sin': ['1:21'],
        'rc://*/tw/dict/bible/kt/fulfill': ['1:22'],
        'rc://*/tw/dict/bible/kt/prophet': ['1:22'],
        'rc://*/tw/dict/bible/other/virgin': ['1:23'],
        'rc://*/tw/dict/bible/other/interpret': ['1:23'],
        'rc://*/tw/dict/bible/kt/god': ['1:23'],
        'rc://*/tw/dict/bible/other/like': ['1:24'],
        'rc://*/tw/dict/bible/other/know': ['1:25'],
      },
    })
  })
})
