const { markRepeatedWords } = require('../src/markRepeatedWords/index')
const { jsonWords } = require('../mocks/mocks')
const { describe, expect, test } = require('@jest/globals')

const shortItems = jsonWords.filter((item) => ['1:1', '1:2'].includes(item.Reference))

describe('markRepeatedWords in verse', () => {
  test('try to mark in verse', () => {
    expect(markRepeatedWords(shortItems)).toEqual([
      {
        Reference: '1:1',
        ID: 'dppb',
        Tags: 'name',
        OrigWords: 'לְ⁠כ֨וֹרֶשׁ֙',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/cyrus',
        isRepeatedInVerse: false,
      },
      {
        Reference: '1:1',
        ID: 'tub4',
        Tags: '',
        OrigWords: 'מֶ֣לֶךְ',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/other/king',
        isRepeatedInVerse: false,
      },
      {
        Reference: '1:1',
        ID: 'zbg7',
        Tags: 'name',
        OrigWords: 'פָּרַ֔ס',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/persia',
        isRepeatedInVerse: false,
      },
      {
        Reference: '1:1',
        ID: 'dx3a',
        Tags: 'keyterm',
        OrigWords: 'יְהוָ֖ה',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/yahweh',
        isRepeatedInVerse: false,
      },
      {
        Reference: '1:1',
        ID: 'jbsg',
        Tags: 'name',
        OrigWords: 'יִרְמְיָ֑ה',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/jeremiah',
        isRepeatedInVerse: false,
      },
      {
        Reference: '1:1',
        ID: 't7m4',
        Tags: 'keyterm',
        OrigWords: 'יְהוָ֗ה',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/yahweh',
        isRepeatedInVerse: true,
      },
      {
        Reference: '1:1',
        ID: 'pk24',
        Tags: 'keyterm',
        OrigWords: 'ר֨וּחַ֙',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/spirit',
        isRepeatedInVerse: false,
      },
      {
        Reference: '1:1',
        ID: 'nyja',
        Tags: 'name',
        OrigWords: 'כֹּ֣רֶשׁ',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/cyrus',
        isRepeatedInVerse: true,
      },
      {
        Reference: '1:1',
        ID: 'f4rq',
        Tags: '',
        OrigWords: 'מֶֽלֶךְ',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/other/king',
        isRepeatedInVerse: true,
      },
      {
        Reference: '1:1',
        ID: 'qs3p',
        Tags: 'name',
        OrigWords: 'פָּרַ֔ס',
        Occurrence: '2',
        TWLink: 'rc://*/tw/dict/bible/names/persia',
        isRepeatedInVerse: true,
      },
      {
        Reference: '1:1',
        ID: 'j29d',
        Tags: '',
        OrigWords: 'מַלְכוּת֔⁠וֹ',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/other/kingdom',
        isRepeatedInVerse: false,
      },
      {
        Reference: '1:2',
        ID: 'jape',
        Tags: 'name',
        OrigWords: 'כֹּ֚רֶשׁ',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/cyrus',
        isRepeatedInVerse: false,
      },
      {
        Reference: '1:2',
        ID: 't456',
        Tags: '',
        OrigWords: 'מֶ֣לֶךְ',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/other/king',
        isRepeatedInVerse: false,
      },
      {
        Reference: '1:2',
        ID: 'rv3c',
        Tags: 'name',
        OrigWords: 'פָּרַ֔ס',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/persia',
        isRepeatedInVerse: false,
      },
      {
        Reference: '1:2',
        ID: 'rmy8',
        Tags: '',
        OrigWords: 'מַמְלְכ֣וֹת',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/other/kingdom',
        isRepeatedInVerse: false,
      },
      {
        Reference: '1:2',
        ID: 'kn78',
        Tags: 'keyterm',
        OrigWords: 'יְהוָ֖ה',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/yahweh',
        isRepeatedInVerse: false,
      },
      {
        Reference: '1:2',
        ID: 'wcdj',
        Tags: 'keyterm',
        OrigWords: 'אֱלֹהֵ֣י',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/god',
        isRepeatedInVerse: false,
      },
      {
        Reference: '1:2',
        ID: 'kf5n',
        Tags: 'keyterm',
        OrigWords: 'הַ⁠שָּׁמָ֑יִם',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/heaven',
        isRepeatedInVerse: false,
      },
      {
        Reference: '1:2',
        ID: 'nrxj',
        Tags: 'keyterm',
        OrigWords: 'פָקַ֤ד',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/appoint',
        isRepeatedInVerse: false,
      },
      {
        Reference: '1:2',
        ID: 'rm6e',
        Tags: 'keyterm',
        OrigWords: 'בַ֔יִת',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/temple',
        isRepeatedInVerse: false,
      },
      {
        Reference: '1:2',
        ID: 'hpk4',
        Tags: 'name',
        OrigWords: 'בִּ⁠ירוּשָׁלִַ֖ם',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/jerusalem',
        isRepeatedInVerse: false,
      },
      {
        Reference: '1:2',
        ID: 'h4aq',
        Tags: 'name',
        OrigWords: 'בִּֽ⁠יהוּדָֽה',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/judea',
        isRepeatedInVerse: false,
      },
    ])
  })
})
describe('markRepeatedWords in chapter', () => {
  test('try to mark in chapter', () => {
    expect(markRepeatedWords(shortItems, 'chapter')).toEqual([
      {
        Reference: '1:1',
        ID: 'dppb',
        Tags: 'name',
        OrigWords: 'לְ⁠כ֨וֹרֶשׁ֙',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/cyrus',
        isRepeatedInChapter: false,
      },
      {
        Reference: '1:1',
        ID: 'tub4',
        Tags: '',
        OrigWords: 'מֶ֣לֶךְ',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/other/king',
        isRepeatedInChapter: false,
      },
      {
        Reference: '1:1',
        ID: 'zbg7',
        Tags: 'name',
        OrigWords: 'פָּרַ֔ס',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/persia',
        isRepeatedInChapter: false,
      },
      {
        Reference: '1:1',
        ID: 'dx3a',
        Tags: 'keyterm',
        OrigWords: 'יְהוָ֖ה',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/yahweh',
        isRepeatedInChapter: false,
      },
      {
        Reference: '1:1',
        ID: 'jbsg',
        Tags: 'name',
        OrigWords: 'יִרְמְיָ֑ה',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/jeremiah',
        isRepeatedInChapter: false,
      },
      {
        Reference: '1:1',
        ID: 't7m4',
        Tags: 'keyterm',
        OrigWords: 'יְהוָ֗ה',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/yahweh',
        isRepeatedInChapter: true,
      },
      {
        Reference: '1:1',
        ID: 'pk24',
        Tags: 'keyterm',
        OrigWords: 'ר֨וּחַ֙',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/spirit',
        isRepeatedInChapter: false,
      },
      {
        Reference: '1:1',
        ID: 'nyja',
        Tags: 'name',
        OrigWords: 'כֹּ֣רֶשׁ',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/cyrus',
        isRepeatedInChapter: true,
      },
      {
        Reference: '1:1',
        ID: 'f4rq',
        Tags: '',
        OrigWords: 'מֶֽלֶךְ',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/other/king',
        isRepeatedInChapter: true,
      },
      {
        Reference: '1:1',
        ID: 'qs3p',
        Tags: 'name',
        OrigWords: 'פָּרַ֔ס',
        Occurrence: '2',
        TWLink: 'rc://*/tw/dict/bible/names/persia',
        isRepeatedInChapter: true,
      },
      {
        Reference: '1:1',
        ID: 'j29d',
        Tags: '',
        OrigWords: 'מַלְכוּת֔⁠וֹ',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/other/kingdom',
        isRepeatedInChapter: false,
      },
      {
        Reference: '1:2',
        ID: 'jape',
        Tags: 'name',
        OrigWords: 'כֹּ֚רֶשׁ',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/cyrus',
        isRepeatedInChapter: true,
      },
      {
        Reference: '1:2',
        ID: 't456',
        Tags: '',
        OrigWords: 'מֶ֣לֶךְ',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/other/king',
        isRepeatedInChapter: true,
      },
      {
        Reference: '1:2',
        ID: 'rv3c',
        Tags: 'name',
        OrigWords: 'פָּרַ֔ס',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/persia',
        isRepeatedInChapter: true,
      },
      {
        Reference: '1:2',
        ID: 'rmy8',
        Tags: '',
        OrigWords: 'מַמְלְכ֣וֹת',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/other/kingdom',
        isRepeatedInChapter: true,
      },
      {
        Reference: '1:2',
        ID: 'kn78',
        Tags: 'keyterm',
        OrigWords: 'יְהוָ֖ה',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/yahweh',
        isRepeatedInChapter: true,
      },
      {
        Reference: '1:2',
        ID: 'wcdj',
        Tags: 'keyterm',
        OrigWords: 'אֱלֹהֵ֣י',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/god',
        isRepeatedInChapter: false,
      },
      {
        Reference: '1:2',
        ID: 'kf5n',
        Tags: 'keyterm',
        OrigWords: 'הַ⁠שָּׁמָ֑יִם',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/heaven',
        isRepeatedInChapter: false,
      },
      {
        Reference: '1:2',
        ID: 'nrxj',
        Tags: 'keyterm',
        OrigWords: 'פָקַ֤ד',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/appoint',
        isRepeatedInChapter: false,
      },
      {
        Reference: '1:2',
        ID: 'rm6e',
        Tags: 'keyterm',
        OrigWords: 'בַ֔יִת',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/temple',
        isRepeatedInChapter: false,
      },
      {
        Reference: '1:2',
        ID: 'hpk4',
        Tags: 'name',
        OrigWords: 'בִּ⁠ירוּשָׁלִַ֖ם',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/jerusalem',
        isRepeatedInChapter: false,
      },
      {
        Reference: '1:2',
        ID: 'h4aq',
        Tags: 'name',
        OrigWords: 'בִּֽ⁠יהוּדָֽה',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/judea',
        isRepeatedInChapter: false,
      },
    ])
  })
})
describe('markRepeatedWords in book', () => {
  test('try to mark in book', () => {
    expect(markRepeatedWords(shortItems, 'book')).toEqual([
      {
        Reference: '1:1',
        ID: 'dppb',
        Tags: 'name',
        OrigWords: 'לְ⁠כ֨וֹרֶשׁ֙',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/cyrus',
        isRepeatedInBook: false,
      },
      {
        Reference: '1:1',
        ID: 'tub4',
        Tags: '',
        OrigWords: 'מֶ֣לֶךְ',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/other/king',
        isRepeatedInBook: false,
      },
      {
        Reference: '1:1',
        ID: 'zbg7',
        Tags: 'name',
        OrigWords: 'פָּרַ֔ס',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/persia',
        isRepeatedInBook: false,
      },
      {
        Reference: '1:1',
        ID: 'dx3a',
        Tags: 'keyterm',
        OrigWords: 'יְהוָ֖ה',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/yahweh',
        isRepeatedInBook: false,
      },
      {
        Reference: '1:1',
        ID: 'jbsg',
        Tags: 'name',
        OrigWords: 'יִרְמְיָ֑ה',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/jeremiah',
        isRepeatedInBook: false,
      },
      {
        Reference: '1:1',
        ID: 't7m4',
        Tags: 'keyterm',
        OrigWords: 'יְהוָ֗ה',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/yahweh',
        isRepeatedInBook: true,
      },
      {
        Reference: '1:1',
        ID: 'pk24',
        Tags: 'keyterm',
        OrigWords: 'ר֨וּחַ֙',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/spirit',
        isRepeatedInBook: false,
      },
      {
        Reference: '1:1',
        ID: 'nyja',
        Tags: 'name',
        OrigWords: 'כֹּ֣רֶשׁ',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/cyrus',
        isRepeatedInBook: true,
      },
      {
        Reference: '1:1',
        ID: 'f4rq',
        Tags: '',
        OrigWords: 'מֶֽלֶךְ',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/other/king',
        isRepeatedInBook: true,
      },
      {
        Reference: '1:1',
        ID: 'qs3p',
        Tags: 'name',
        OrigWords: 'פָּרַ֔ס',
        Occurrence: '2',
        TWLink: 'rc://*/tw/dict/bible/names/persia',
        isRepeatedInBook: true,
      },
      {
        Reference: '1:1',
        ID: 'j29d',
        Tags: '',
        OrigWords: 'מַלְכוּת֔⁠וֹ',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/other/kingdom',
        isRepeatedInBook: false,
      },
      {
        Reference: '1:2',
        ID: 'jape',
        Tags: 'name',
        OrigWords: 'כֹּ֚רֶשׁ',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/cyrus',
        isRepeatedInBook: true,
      },
      {
        Reference: '1:2',
        ID: 't456',
        Tags: '',
        OrigWords: 'מֶ֣לֶךְ',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/other/king',
        isRepeatedInBook: true,
      },
      {
        Reference: '1:2',
        ID: 'rv3c',
        Tags: 'name',
        OrigWords: 'פָּרַ֔ס',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/persia',
        isRepeatedInBook: true,
      },
      {
        Reference: '1:2',
        ID: 'rmy8',
        Tags: '',
        OrigWords: 'מַמְלְכ֣וֹת',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/other/kingdom',
        isRepeatedInBook: true,
      },
      {
        Reference: '1:2',
        ID: 'kn78',
        Tags: 'keyterm',
        OrigWords: 'יְהוָ֖ה',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/yahweh',
        isRepeatedInBook: true,
      },
      {
        Reference: '1:2',
        ID: 'wcdj',
        Tags: 'keyterm',
        OrigWords: 'אֱלֹהֵ֣י',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/god',
        isRepeatedInBook: false,
      },
      {
        Reference: '1:2',
        ID: 'kf5n',
        Tags: 'keyterm',
        OrigWords: 'הַ⁠שָּׁמָ֑יִם',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/heaven',
        isRepeatedInBook: false,
      },
      {
        Reference: '1:2',
        ID: 'nrxj',
        Tags: 'keyterm',
        OrigWords: 'פָקַ֤ד',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/appoint',
        isRepeatedInBook: false,
      },
      {
        Reference: '1:2',
        ID: 'rm6e',
        Tags: 'keyterm',
        OrigWords: 'בַ֔יִת',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/temple',
        isRepeatedInBook: false,
      },
      {
        Reference: '1:2',
        ID: 'hpk4',
        Tags: 'name',
        OrigWords: 'בִּ⁠ירוּשָׁלִַ֖ם',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/jerusalem',
        isRepeatedInBook: false,
      },
      {
        Reference: '1:2',
        ID: 'h4aq',
        Tags: 'name',
        OrigWords: 'בִּֽ⁠יהוּדָֽה',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/judea',
        isRepeatedInBook: false,
      },
    ])
  })
})
describe('markRepeatedWords for all', () => {
  test('try to mark in book, chapter and verse', () => {
    expect(markRepeatedWords(shortItems, 'all')).toEqual([
      {
        Reference: '1:1',
        ID: 'dppb',
        Tags: 'name',
        OrigWords: 'לְ⁠כ֨וֹרֶשׁ֙',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/cyrus',
        isRepeatedInVerse: false,
        isRepeatedInChapter: false,
        isRepeatedInBook: false,
      },
      {
        Reference: '1:1',
        ID: 'tub4',
        Tags: '',
        OrigWords: 'מֶ֣לֶךְ',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/other/king',
        isRepeatedInVerse: false,
        isRepeatedInChapter: false,
        isRepeatedInBook: false,
      },
      {
        Reference: '1:1',
        ID: 'zbg7',
        Tags: 'name',
        OrigWords: 'פָּרַ֔ס',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/persia',
        isRepeatedInVerse: false,
        isRepeatedInChapter: false,
        isRepeatedInBook: false,
      },
      {
        Reference: '1:1',
        ID: 'dx3a',
        Tags: 'keyterm',
        OrigWords: 'יְהוָ֖ה',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/yahweh',
        isRepeatedInVerse: false,
        isRepeatedInChapter: false,
        isRepeatedInBook: false,
      },
      {
        Reference: '1:1',
        ID: 'jbsg',
        Tags: 'name',
        OrigWords: 'יִרְמְיָ֑ה',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/jeremiah',
        isRepeatedInVerse: false,
        isRepeatedInChapter: false,
        isRepeatedInBook: false,
      },
      {
        Reference: '1:1',
        ID: 't7m4',
        Tags: 'keyterm',
        OrigWords: 'יְהוָ֗ה',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/yahweh',
        isRepeatedInVerse: true,
        isRepeatedInChapter: true,
        isRepeatedInBook: true,
      },
      {
        Reference: '1:1',
        ID: 'pk24',
        Tags: 'keyterm',
        OrigWords: 'ר֨וּחַ֙',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/spirit',
        isRepeatedInVerse: false,
        isRepeatedInChapter: false,
        isRepeatedInBook: false,
      },
      {
        Reference: '1:1',
        ID: 'nyja',
        Tags: 'name',
        OrigWords: 'כֹּ֣רֶשׁ',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/cyrus',
        isRepeatedInVerse: true,
        isRepeatedInChapter: true,
        isRepeatedInBook: true,
      },
      {
        Reference: '1:1',
        ID: 'f4rq',
        Tags: '',
        OrigWords: 'מֶֽלֶךְ',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/other/king',
        isRepeatedInVerse: true,
        isRepeatedInChapter: true,
        isRepeatedInBook: true,
      },
      {
        Reference: '1:1',
        ID: 'qs3p',
        Tags: 'name',
        OrigWords: 'פָּרַ֔ס',
        Occurrence: '2',
        TWLink: 'rc://*/tw/dict/bible/names/persia',
        isRepeatedInVerse: true,
        isRepeatedInChapter: true,
        isRepeatedInBook: true,
      },
      {
        Reference: '1:1',
        ID: 'j29d',
        Tags: '',
        OrigWords: 'מַלְכוּת֔⁠וֹ',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/other/kingdom',
        isRepeatedInVerse: false,
        isRepeatedInChapter: false,
        isRepeatedInBook: false,
      },
      {
        Reference: '1:2',
        ID: 'jape',
        Tags: 'name',
        OrigWords: 'כֹּ֚רֶשׁ',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/cyrus',
        isRepeatedInVerse: false,
        isRepeatedInChapter: true,
        isRepeatedInBook: true,
      },
      {
        Reference: '1:2',
        ID: 't456',
        Tags: '',
        OrigWords: 'מֶ֣לֶךְ',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/other/king',
        isRepeatedInVerse: false,
        isRepeatedInChapter: true,
        isRepeatedInBook: true,
      },
      {
        Reference: '1:2',
        ID: 'rv3c',
        Tags: 'name',
        OrigWords: 'פָּרַ֔ס',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/persia',
        isRepeatedInVerse: false,
        isRepeatedInChapter: true,
        isRepeatedInBook: true,
      },
      {
        Reference: '1:2',
        ID: 'rmy8',
        Tags: '',
        OrigWords: 'מַמְלְכ֣וֹת',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/other/kingdom',
        isRepeatedInVerse: false,
        isRepeatedInChapter: true,
        isRepeatedInBook: true,
      },
      {
        Reference: '1:2',
        ID: 'kn78',
        Tags: 'keyterm',
        OrigWords: 'יְהוָ֖ה',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/yahweh',
        isRepeatedInVerse: false,
        isRepeatedInChapter: true,
        isRepeatedInBook: true,
      },
      {
        Reference: '1:2',
        ID: 'wcdj',
        Tags: 'keyterm',
        OrigWords: 'אֱלֹהֵ֣י',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/god',
        isRepeatedInVerse: false,
        isRepeatedInChapter: false,
        isRepeatedInBook: false,
      },
      {
        Reference: '1:2',
        ID: 'kf5n',
        Tags: 'keyterm',
        OrigWords: 'הַ⁠שָּׁמָ֑יִם',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/heaven',
        isRepeatedInVerse: false,
        isRepeatedInChapter: false,
        isRepeatedInBook: false,
      },
      {
        Reference: '1:2',
        ID: 'nrxj',
        Tags: 'keyterm',
        OrigWords: 'פָקַ֤ד',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/appoint',
        isRepeatedInVerse: false,
        isRepeatedInChapter: false,
        isRepeatedInBook: false,
      },
      {
        Reference: '1:2',
        ID: 'rm6e',
        Tags: 'keyterm',
        OrigWords: 'בַ֔יִת',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/kt/temple',
        isRepeatedInVerse: false,
        isRepeatedInChapter: false,
        isRepeatedInBook: false,
      },
      {
        Reference: '1:2',
        ID: 'hpk4',
        Tags: 'name',
        OrigWords: 'בִּ⁠ירוּשָׁלִַ֖ם',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/jerusalem',
        isRepeatedInVerse: false,
        isRepeatedInChapter: false,
        isRepeatedInBook: false,
      },
      {
        Reference: '1:2',
        ID: 'h4aq',
        Tags: 'name',
        OrigWords: 'בִּֽ⁠יהוּדָֽה',
        Occurrence: '1',
        TWLink: 'rc://*/tw/dict/bible/names/judea',
        isRepeatedInVerse: false,
        isRepeatedInChapter: false,
        isRepeatedInBook: false,
      },
    ])
  })
})
